x-common-variables: &common-variables
  environment:
    # Hostnames used to connect services to each other.
    # They are taken from the .env file since they are also used in the docker-compose.yaml.
    DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
    RABBITMQ_HOSTNAME: ${RABBITMQ_HOSTNAME}
    PROXY_HOSTNAME: ${PROXY_HOSTNAME}
    MAGNETIC_REEDS_LISTENER_HOSTNAME: ${MAGNETIC_REEDS_LISTENER_HOSTNAME}
    # Paths of files where credentials are saved.
    # They are saved in the shared volume so every service can use them.
    PG_CREDENTIALS_FILE: shared/pg_credentials.json
    RBBT_CREDENTIALS_FILE: shared/rbbt_credentials.json

services:
  database:
    image: postgres:16.4
    <<: *common-variables
    hostname: ${DATABASE_HOSTNAME}
    volumes:
      - db-data:/var/lib/postgresql/data
      - shared:/shared
      - ./other-entrypoints/database_entrypoint.sh:/usr/bin/database_entrypoint.sh
    expose:
      - "5432"
    command: ["/bin/bash", "/usr/bin/database_entrypoint.sh"]
    restart: on-failure

  rabbitmq:
    image: rabbitmq:3.13.7
    <<: *common-variables
    hostname: ${RABBITMQ_HOSTNAME}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/data
      - shared:/shared
      - ./other-entrypoints/rabbitmq_entrypoint.sh:/usr/bin/rabbitmq_entrypoint.sh
    expose:
      - "5672"
    command: ["/bin/bash", "/usr/bin/rabbitmq_entrypoint.sh"]
    restart: on-failure

  proxy:
    build: microservices/project-proxy
    <<: *common-variables
    hostname: ${PROXY_HOSTNAME}
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - proxy-data:/var/lib/proxy/data
      - shared:/shared
    restart: on-failure

  reeds-listener:
    build: microservices/magnetic-reeds-listener
    <<: *common-variables
    hostname: ${MAGNETIC_REEDS_LISTENER_HOSTNAME}
    expose:
      - "8000"
    depends_on:
      - database
    volumes:
      - reeds-listener-data:/var/lib/reeds-listener/data
      - shared:/shared
    restart: on-failure

volumes:
  db-data:
  rabbitmq-data:
  shared:
  proxy-data:
  reeds-listener-data:
