x-common-variables: &common-variables
  environment:
    # Paths of files where credentials are saved.
    # They are saved in the shared volume so every service can use them.
    PG_CREDENTIALS_FILE: /shared/pg_credentials.json
    NTFY_CREDENTIALS_FILE: /shared/ntfy_credentials.json
    # The secret key does not need to be shared between services
    AUTH_SECRET_KEY_FILE: /var/lib/auth-data/data/private_key.json

services:
  database:
    image: postgres:16.4
    <<: *common-variables
    hostname: db
    volumes:
      - db-data:/var/lib/postgresql/data
      - shared:/shared
      - ./other-entrypoints/database_entrypoint.sh:/usr/bin/database_entrypoint.sh
    command: [ "/bin/bash", "/usr/bin/database_entrypoint.sh" ]
    restart: unless-stopped
    expose:
      - "5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U project-user -d project-database" ]
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 5s

  devices-manager:
    build: microservices/devices-manager
    <<: *common-variables
    hostname: devices-manager
    volumes:
      - devices-manager-data:/var/lib/devices-manager/data
      - shared:/shared
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      local-audio-manager:
        condition: service_started
      notifications-manager:
        condition: service_started
    expose:
      - "8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  notifications-manager:
    build: microservices/notifications-manager
    <<: *common-variables
    hostname: notifications-manager
    volumes:
      - notifications-manager-data:/var/lib/notifications-manager/data
      - shared:/shared
    restart: unless-stopped
    depends_on:
      ntfy:
        condition: service_started
      database:
        condition: service_healthy
    expose:
      - "8000"

  local-audio-manager:
    build: microservices/local-audio-manager
    <<: *common-variables
    hostname: local-audio-manager
    volumes:
      - local-audio-manager-data:/var/lib/local-audio-manager/data
      - shared:/shared
    restart: unless-stopped
    expose:
      - "8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  irrigation-manager:
    build: microservices/irrigation-manager
    <<: *common-variables
    hostname: irrigation-manager
    volumes:
      - shared:/shared
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    expose:
      - "8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  auth:
    build: microservices/project-auth
    <<: *common-variables
    hostname: project-auth
    volumes:
      - auth-data:/var/lib/auth-data/data
      - shared:/shared
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
    expose:
      - "8000"

  frontend:
    build: microservices/project-frontend
    <<: *common-variables
    hostname: frontend
    volumes:
      - shared:/shared
    expose:
      - "3000"
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
      devices-manager:
        condition: service_started
      local-audio-manager:
        condition: service_started
      irrigation-manager:
        condition: service_started
      auth:
        condition: service_started
      notifications-manager:
        condition: service_started

  ntfy:
    image: binwiederhier/ntfy:v2.11.0
    <<: *common-variables
    hostname: ntfy
    volumes:
      - /var/lib/ntfy:/var/lib/ntfy
      - ntfy-data:/var/lib/ntfy/data
      - shared:/shared
      - ./other-entrypoints/ntfy_entrypoint.sh:/usr/bin/ntfy_entrypoint.sh
    entrypoint: [ "/bin/ash", "/usr/bin/ntfy_entrypoint.sh" ]
    restart: unless-stopped
    expose:
      - "80"

  health-checker:
    image: alpine:3.19
    <<: *common-variables
    hostname: health-checker
    volumes:
      - ./other-entrypoints/health_checker_entrypoint.sh:/health_checker_entrypoint.sh:ro
    command: [ "/bin/sh", "-c", "apk add --no-cache bash curl && bash /health_checker_entrypoint.sh" ]
    restart: unless-stopped
    expose:
      - "8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:1.28.0-alpine
    <<: *common-variables
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-init:/docker-entrypoint.d:ro
      - nginx-ssl:/etc/nginx/ssl
    depends_on:
      - frontend
    restart: unless-stopped

volumes:
  db-data:
  shared:
  devices-manager-data:
  notifications-manager-data:
  local-audio-manager-data:
  auth-data:
  ntfy-data:
  nginx-ssl: