x-common-variables: &common-variables
  environment:
    # Hostnames used to connect services to each other.
    # They are taken from the .env file since they are also used in the docker-compose.yaml.
    DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
    RABBITMQ_HOSTNAME: ${RABBITMQ_HOSTNAME}
    PROXY_HOSTNAME: ${PROXY_HOSTNAME}
    DEVICES_MANAGER_HOSTNAME: ${DEVICES_MANAGER_HOSTNAME}
    NOTIFICATIONS_MANAGER_HOSTNAME: ${NOTIFICATIONS_MANAGER_HOSTNAME}
    LOCAL_AUDIO_MANAGER_HOSTNAME: ${LOCAL_AUDIO_MANAGER_HOSTNAME}
    AUTH_HOSTNAME: ${AUTH_HOSTNAME}
    FRONTEND_HOSTNAME: ${FRONTEND_HOSTNAME}
    NTFY_HOSTNAME: ${NTFY_HOSTNAME}
    LOCALTUNNEL_HOSTNAME: ${LOCALTUNNEL_HOSTNAME}
    # Paths of files where credentials are saved.
    # They are saved in the shared volume so every service can use them.
    PG_CREDENTIALS_FILE: /shared/pg_credentials.json
    RBBT_CREDENTIALS_FILE: /shared/rbbt_credentials.json
    NTFY_CREDENTIALS_FILE: /shared/ntfy_credentials.json
    LT_CREDENTIALS_FILE: /shared/lt_credentials.json
    # The secret key does not need to be shared between services
    AUTH_SECRET_KEY_FILE: /var/lib/auth-data/data/private_key.json

services:
  # DEV services with ports reachable from host
  database-dev:
    image: postgres:16.4
    <<: *common-variables
    hostname: ${DATABASE_HOSTNAME}
    volumes:
      - db-data:/var/lib/postgresql/data
      - shared:/shared
      - ./other-entrypoints/database_entrypoint.sh:/usr/bin/database_entrypoint.sh
    command: [ "/bin/bash", "/usr/bin/database_entrypoint.sh" ]
    restart: on-failure
    ports:
      - "5432:5432"

  rabbitmq-dev:
    image: rabbitmq:3.13.7-management
    <<: *common-variables
    hostname: ${RABBITMQ_HOSTNAME}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/data
      - shared:/shared
      - ./other-entrypoints/rabbitmq_entrypoint.sh:/usr/bin/rabbitmq_entrypoint.sh
    command: [ "/bin/bash", "/usr/bin/rabbitmq_entrypoint.sh" ]
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"

  proxy-dev:
    build: microservices/project-proxy
    <<: *common-variables
    hostname: ${PROXY_HOSTNAME}
    volumes:
      - proxy-data:/var/lib/proxy/data
      - shared:/shared
    restart: on-failure
    ports:
      - "8000:8000"

  localtunnel-dev:
    image: node:16
    <<: *common-variables
    network_mode: host
    hostname: ${LOCALTUNNEL_HOSTNAME}
    volumes:
      - localtunnel-data:/var/lib/localtunnel/data
      - shared:/shared
      - ./other-entrypoints/localtunnel_entrypoint.sh:/usr/bin/localtunnel_entrypoint.sh
    entrypoint: [ "/bin/bash", "/usr/bin/localtunnel_entrypoint.sh" ]
    restart: on-failure

  devices-manager-dev:
    build: microservices/devices-manager
    <<: *common-variables
    hostname: ${DEVICES_MANAGER_HOSTNAME}
    volumes:
      - devices-manager-data:/var/lib/devices-manager/data
      - shared:/shared
    restart: on-failure
    depends_on:
      - database-dev
      - rabbitmq-dev
      - localtunnel-dev
    ports:
      - "8001:8000"
    privileged: true

  notifications-manager-dev:
    build: microservices/notifications-manager
    <<: *common-variables
    hostname: ${NOTIFICATIONS_MANAGER_HOSTNAME}
    volumes:
      - notifications-manager-data:/var/lib/notifications-manager/data
      - shared:/shared
    restart: on-failure
    depends_on:
      - rabbitmq-dev
      - localtunnel-dev
    ports:
      - "8002:8000"

  local-audio-manager-dev:
    build: microservices/local-audio-manager
    <<: *common-variables
    hostname: ${LOCAL_AUDIO_MANAGER_HOSTNAME}
    volumes:
      - local-audio-manager-data:/var/lib/local-audio-manager/data
      - shared:/shared
    restart: on-failure
    depends_on:
      - rabbitmq-dev
      - localtunnel-dev
    ports:
      - "8003:8000"
    devices:
      - /dev/snd:/dev/snd

  auth-dev:
    build: microservices/project-auth
    <<: *common-variables
    hostname: ${AUTH_HOSTNAME}
    volumes:
      - auth-data:/var/lib/auth-data/data
      - shared:/shared
    restart: on-failure
    depends_on:
      - database-dev
      - rabbitmq-dev
      - localtunnel-dev
    ports:
      - "8004:8000"

  frontend-dev:
    build: microservices/project-frontend
    <<: *common-variables
    hostname: ${FRONTEND_HOSTNAME}
    volumes:
      - shared:/shared
    ports:
      - "80:3000"
    restart: on-failure
    depends_on:
      - database-dev
      - rabbitmq-dev
      - devices-manager-dev
      - local-audio-manager-dev
      - auth-dev
      - notifications-manager-dev
      - proxy-dev
      - localtunnel-dev

  ntfy-dev:
    image: binwiederhier/ntfy:v2.11.0
    <<: *common-variables
    hostname: ${NTFY_HOSTNAME}
    volumes:
      - /var/lib/ntfy:/var/lib/ntfy
      - ntfy-data:/var/lib/ntfy/data
      - shared:/shared
      - ./other-entrypoints/ntfy_entrypoint.sh:/usr/bin/ntfy_entrypoint.sh
    entrypoint: [ "/bin/ash", "/usr/bin/ntfy_entrypoint.sh" ]
    restart: on-failure
    depends_on:
      - localtunnel-dev
    ports:
      - "8080:80"

volumes:
  db-data:
  rabbitmq-data:
  shared:
  proxy-data:
  devices-manager-data:
  notifications-manager-data:
  local-audio-manager-data:
  auth-data:
  ntfy-data:
  localtunnel-data:
