x-common-variables: &common-variables
  environment:
    # Hostnames used to connect services to each other.
    # They are taken from the .env file since they are also used in the docker-compose.yaml.
    DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
    RABBITMQ_HOSTNAME: ${RABBITMQ_HOSTNAME}
    PROXY_HOSTNAME: ${PROXY_HOSTNAME}
    MAGNETIC_REEDS_LISTENER_HOSTNAME: ${MAGNETIC_REEDS_LISTENER_HOSTNAME}
    RTSP_CAMERAS_LISTENER_HOSTNAME: ${RTSP_CAMERAS_LISTENER_HOSTNAME}
    # Paths of files where credentials are saved.
    # They are saved in the shared volume so every service can use them.
    PG_CREDENTIALS_FILE: /shared/pg_credentials.json
    RBBT_CREDENTIALS_FILE: /shared/rbbt_credentials.json

services:
  # DEV services with ports reachable from host
  database-dev:
    image: postgres:16.4
    <<: *common-variables
    hostname: ${DATABASE_HOSTNAME}
    volumes:
      - db-data:/var/lib/postgresql/data
      - shared:/shared
      - ./other-entrypoints/database_entrypoint.sh:/usr/bin/database_entrypoint.sh
    command: [ "/bin/bash", "/usr/bin/database_entrypoint.sh" ]
    restart: on-failure
    ports:
      - "5432:5432"
    profiles:
      - raspberry
      - not-raspberry

  rabbitmq-dev:
    image: rabbitmq:3.13.7-management
    <<: *common-variables
    hostname: ${RABBITMQ_HOSTNAME}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/data
      - shared:/shared
      - ./other-entrypoints/rabbitmq_entrypoint.sh:/usr/bin/rabbitmq_entrypoint.sh
    command: [ "/bin/bash", "/usr/bin/rabbitmq_entrypoint.sh" ]
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    profiles:
      - raspberry
      - not-raspberry

  proxy-dev:
    build: microservices/project-proxy
    <<: *common-variables
    hostname: ${PROXY_HOSTNAME}
    volumes:
      - proxy-data:/var/lib/proxy/data
      - shared:/shared
    restart: on-failure
    depends_on:
      - database-dev
    ports:
      - "8000:8000"
    profiles:
      - raspberry
      - not-raspberry

  reeds-listener-dev:
    build: microservices/magnetic-reeds-listener
    <<: *common-variables
    hostname: ${MAGNETIC_REEDS_LISTENER_HOSTNAME}
    volumes:
      - reeds-listener-data:/var/lib/reeds-listener/data
      - shared:/shared
    restart: on-failure
    depends_on:
      - database-dev
    ports:
      - "8001:8000"
    profiles:
      - raspberry
    privileged: true

  cameras-listener-dev:
    build: microservices/rtsp-cameras-listener
    <<: *common-variables
    hostname: ${RTSP_CAMERAS_LISTENER_HOSTNAME}
    volumes:
      - cameras-listener-data:/var/lib/cameras-listener/data
      - shared:/shared
    restart: on-failure
    ports:
      - "8002:8000"
    depends_on:
      - database-dev
    profiles:
      - raspberry
      - not-raspberry

volumes:
  db-data:
  rabbitmq-data:
  shared:
  proxy-data:
  reeds-listener-data:
  cameras-listener-data:
