x-common-variables: &common-variables
  environment:
    # Hostnames used to connect services to each other.
    # They are taken from the .env file since they are also used in the docker-compose.yaml.
    DATABASE_HOSTNAME: ${DATABASE_HOSTNAME}
    RABBITMQ_HOSTNAME: ${RABBITMQ_HOSTNAME}
    PROXY_HOSTNAME: ${PROXY_HOSTNAME}
    MAGNETIC_REEDS_LISTENER_HOSTNAME: ${MAGNETIC_REEDS_LISTENER_HOSTNAME}
    RTSP_CAMERAS_LISTENER_HOSTNAME: ${RTSP_CAMERAS_LISTENER_HOSTNAME}
    MAIL_NOTIFICATIONS_HOSTNAME: ${MAIL_NOTIFICATIONS_HOSTNAME}
    LOCAL_AUDIO_MANAGER_HOSTNAME: ${LOCAL_AUDIO_MANAGER_HOSTNAME}
    # Paths of files where credentials are saved.
    # They are saved in the shared volume so every service can use them.
    PG_CREDENTIALS_FILE: /shared/pg_credentials.json
    RBBT_CREDENTIALS_FILE: /shared/rbbt_credentials.json

services:
  database:
    image: postgres:16.4
    <<: *common-variables
    hostname: ${DATABASE_HOSTNAME}
    volumes:
      - db-data:/var/lib/postgresql/data
      - shared:/shared
      - ./other-entrypoints/database_entrypoint.sh:/usr/bin/database_entrypoint.sh
    command: [ "/bin/bash", "/usr/bin/database_entrypoint.sh" ]
    restart: on-failure
    expose:
      - "5432"
    profiles:
      - raspberry
      - not-raspberry

  rabbitmq:
    image: rabbitmq:3.13.7-management
    <<: *common-variables
    hostname: ${RABBITMQ_HOSTNAME}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/data
      - shared:/shared
      - ./other-entrypoints/rabbitmq_entrypoint.sh:/usr/bin/rabbitmq_entrypoint.sh
    command: [ "/bin/bash", "/usr/bin/rabbitmq_entrypoint.sh" ]
    restart: on-failure
    expose:
      - "5672"
    profiles:
      - raspberry
      - not-raspberry

  proxy:
    build: microservices/project-proxy
    <<: *common-variables
    hostname: ${PROXY_HOSTNAME}
    volumes:
      - proxy-data:/var/lib/proxy/data
      - shared:/shared
    restart: on-failure
    ports:
      - "8000:8000"
    profiles:
      - raspberry
      - not-raspberry

  reeds-listener:
    build: microservices/magnetic-reeds-listener
    <<: *common-variables
    hostname: ${MAGNETIC_REEDS_LISTENER_HOSTNAME}
    volumes:
      - reeds-listener-data:/var/lib/reeds-listener/data
      - shared:/shared
    restart: on-failure
    expose:
      - "8000"
    depends_on:
      - database
    profiles:
      - raspberry
    privileged: true

  cameras-listener:
    build: microservices/rtsp-cameras-listener
    <<: *common-variables
    hostname: ${RTSP_CAMERAS_LISTENER_HOSTNAME}
    volumes:
      - cameras-listener-data:/var/lib/cameras-listener/data
      - shared:/shared
    restart: on-failure
    expose:
      - "8000"
    depends_on:
      - database
    profiles:
      - raspberry
      - not-raspberry

  mail-notifications:
    build: microservices/mail-notifications
    <<: *common-variables
    hostname: ${MAIL_NOTIFICATIONS_HOSTNAME}
    volumes:
      - mail-notifications-data:/var/lib/mail-notifications/data
      - shared:/shared
    restart: on-failure
    expose:
      - "8000"
    profiles:
      - raspberry
      - not-raspberry

  local-audio-manager:
    build: microservices/local-audio-manager
    <<: *common-variables
    hostname: ${LOCAL_AUDIO_MANAGER_HOSTNAME}
    environment:
      - PULSE_SERVER=tcp:host.docker.internal:4713
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - local-audio-manager-data:/var/lib/local-audio-manager/data
      - shared:/shared
    restart: on-failure
    expose:
      - "8000"
    profiles:
      - raspberry
      - not-raspberry

volumes:
  db-data:
  rabbitmq-data:
  shared:
  proxy-data:
  reeds-listener-data:
  cameras-listener-data:
  mail-notifications-data:
  local-audio-manager-data: